name = "Prometheus"
uuid = "f25c1797-fe98-4e0c-b252-1b4fe3b6bde6"
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
HTTP = "1"
Sockets = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
