name = "Prometheus"
uuid = "f25c1797-fe98-4e0c-b252-1b4fe3b6bde6"
version = "1.0.1"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
SimpleBufferStream = "777ac1f9-54b0-4bf8-805c-2214025038e7"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
CodecZlib = "0.7"
HTTP = "1"
SimpleBufferStream = "1"
Sockets = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
